// Generated by https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/data-model
// Do not modify manually.

export interface Category {
  id: number
  name: string
  parentId?: number | null
  createdAt: Date
  updatedAt: Date
  parent?: Category | null
  children: Category[]
  products: ProductCategory[]
}

export interface Product {
  id: number
  name: string
  price: number
  description?: string | null
  details?: string | null
  createdAt: Date
  updatedAt: Date
  variations: Variation[]
  categories: ProductCategory[]
  productVariationTypes: ProductVariationType[]
  orderProduct: OrderProduct[]
  cartProduct: CartProduct[]
}

export interface ProductCategory {
  productId: number
  categoryId: number
  product: Product
  category: Category
}

export interface VariationType {
  id: number
  name: string
  component: string
  required: boolean
  createdAt: Date
  updatedAt: Date
  variations: Variation[]
  productVariationType: ProductVariationType[]
}

export interface ProductVariationType {
  product: Product
  variationType: VariationType
  productId: number
  variationTypeId: number
}

export interface Variation {
  id: number
  name: string
  value?: string | null
  slug?: string | null
  price: number
  createdAt: Date
  updatedAt: Date
  parentId?: number | null
  typeId: number
  productId: number
  parent?: Variation | null
  children: Variation[]
  type: VariationType
  Product?: Product | null
  orderVariations: OrderVariation[]
  stock: Stock[]
  availableStock?: AvailableStock | null
  cartProductVariation: CartProductVariation[]
}

export interface Stock {
  id: number
  variationId: number
  quantity: number
  createdAt: Date
  updatedAt: Date
  variation: Variation
}

export interface AvailableStock {
  id: number
  variationId: number
  quantity: number
  createdAt: Date
  updatedAt: Date
  variation: Variation
}

export interface Customer {
  id: number
  email: string
  phone?: string | null
  name: string
  password: string
  refreshToken?: string | null
  createdAt: Date
  updatedAt: Date
  orders: Order[]
  cart?: Cart | null
}

export interface Cart {
  id: number
  customerId: number
  createdAt: Date
  updatedAt: Date
  customer: Customer
  cartProducts: CartProduct[]
}

export interface CartProduct {
  id: number
  productId: number
  cartId: number
  quantity: number
  createdAt: Date
  updatedAt: Date
  product: Product
  cart: Cart
  variations: CartProductVariation[]
}

export interface CartProductVariation {
  variationId: number
  quantity: number
  cartProductId: number
  cartProduct: CartProduct
  variation: Variation
}

export interface Order {
  id: number
  customerId?: number | null
  createdAt: Date
  updatedAt: Date
  customer?: Customer | null
  orderProduct: OrderProduct[]
  orderStatuses?: Array<OrderStatus>
}

export interface OrderStatus {
  id: number
  orderId?: number
  status: number
  createdAt: Date
  updatedAt: Date
  order: Order
}

export interface OrderProduct {
  id: number
  productId: number
  orderId: number
  createdAt: Date
  updatedAt: Date
  product: Product
  order: Order
  OrderVariation: OrderVariation[]
}

export interface OrderVariation {
  id: number
  variationId: number
  orderProductId: number
  createdAt: Date
  updatedAt: Date
  orderProduct: OrderProduct
  variation: Variation
}

export interface Media {
  id: number
  filename: string
  mimetype: string
  encoding: string
  url: string
  size: number
  objectId: number
  objectType: string
  createdAt: Date
  updatedAt: Date
}
